mode_profiles:
  standard:
    mbf_controller_name: "MPPI_Standard_Controller"
    actuator_profile_name: "standard"
    default_clean_mode: "scrub"

  heavy:
    mbf_controller_name: "MPPI_Heavy_Controller"
    actuator_profile_name: "heavy"
    default_clean_mode: "scrub"

  eco:
    mbf_controller_name: "MPPI_Eco_Controller"
    actuator_profile_name: "eco"
    default_clean_mode: "scrub"
