uint8 START = 0
uint8 PAUSE = 1
uint8 CONTINUE = 2
uint8 STOP = 3
uint8 RETURN = 4

uint8 command # START PAUSE CONTINUE STOP RETURN
int32 task_id #只有在START时才需要

---

bool success
string message

# START: 指定task_id, 随后任务开始运行
# PAUSE: 暂停任务
# CONTINUE: 继续任务
# STOP: 结束任务,并清空缓存路径
# RETURN: 返回补水站, 必须在PAUSE或STOP后使用

# 前端:
# 名称: "/exe_task_server"
# type: 
