uint8 get = 0
uint8 add = 1
uint8 modify = 2
uint8 Delete = 3
uint8 getAll = 4

uint8 operation # get; add; modify; Delete; getAll;
int32 id
CcppPath cpath
int32 mapId
---

CcppPath cpath
CcppPath[] cpaths
bool success

# get: 指定 id; 返回 cpath
# add: 指定 cpath (cpath中的id会自动分配)
# modify: 指定 cpath (cpath中的id不变)
# Delete: 指定 id
# getAll: 返回所有 cpaths

# 前端:
# 名称: "/database_server/ccpp_service"