uint8 get = 0
uint8 add = 1
uint8 modify = 2
uint8 Delete = 3
uint8 getAll = 4
uint8 activate = 5

uint8 operation
string map_name
string alignment_version
MapAlignmentConfig config
---
bool success
string message
MapAlignmentConfig config
MapAlignmentConfig[] configs
