uint8 add = 0
uint8 modify = 1
uint8 Delete = 2
uint8 getAll = 3

uint8 operation # add; modify; Delete; getAll;
VirtualWall wall # 只有add、modify操作才有数据
int32 delete_id # 只有Delete操作才有数据
int32 mapId
---

bool success
string message
VirtualWall[] walls # 只有getAll操作才会有数据

# add: 指定wall
# modify: 指定wall
# Delete: 指定delete_name
# getAll: 返回所有walls

# 前端:
# 名称: /database_server/vwall_service