uint8 add = 0
uint8 modify = 1
uint8 Delete = 2
uint8 getAll = 3

uint8 operation # add; modify; Delete; getAll;
ProhibitionArea area # 只有add、modify操作才有数据
int32 delete_id # 只有Delete操作才有数据
int32 mapId
---

bool success
string message
ProhibitionArea[] areas # 只有getAll操作才会有数据

# add: 指定 area
# modify: 指定 area
# Delete: 指定delete_name
# getAll: 返回所有 areas

# 前端:
# 名称: /database_server/prohibit_service