string map_name
string alignment_version
geometry_msgs/Point32 p1
geometry_msgs/Point32 p2
float64 min_side_m
---
bool success
string message
string alignment_version
string display_frame
string storage_frame
PolygonRegion display_region
PolygonRegion map_region
float64 width_m
float64 height_m
float64 area_m2
bool valid
string[] warnings
