uint8 START = 0
uint8 STOP = 1

uint8 operation # START; STOP;
string name # STOP 时传入
# uint8 type  # 示教类型: 0-原始路径; 1-覆盖路径
# uint8 coverage_type # type==1时生效, 覆盖类型: 0-弓字形; 1-回字形
# int32 interval  # type==1时生效, cell间隔决定路径的间距
# int32 free_threshold # type==1时生效, 路径接近障碍程度: [1, 254], 值越小路径越远离障碍, 一般取值30

---

my_msg_srv/TeachPath path  # 原始示教路径, stop时传入
bool success
string message

# 示教模式记录路径服务：
# START: 开始记录路径，同时发布路径数据
# STOP: 指定name，type, 结束记录路径同时保存

# 前端:
# 名称: "/clean_robot_server/record_task"
# type: 