geometry_msgs/Polygon Polygon
string name
int32 id
int8 mode # 0: 弓字形路径; 1: 回字形路径
int32 interval # cell间隔决定路径的间距: 一般取值10,可以上下调整
int32 free_threshold # 路径接近障碍程度: [1, 254], 值越小路径越远离障碍, 一般取值30

---

string serialized_path
bool success
string message

# 前端:
# 名称: ""