string map_name
string map_revision_id
string zone_id
string alignment_version
string plan_profile_name
---
bool success
string message
string map_revision_id
string zone_id
string active_plan_id
string plan_profile_name
string alignment_version
string display_frame
string storage_frame
PolygonRing display_path
PolygonRing map_path
geometry_msgs/Pose2D display_entry_pose
geometry_msgs/Pose2D entry_pose
float64 estimated_length_m
float64 estimated_duration_s
string[] warnings
