# Fixed commercial dynamic-loader search paths for x86_64 Ubuntu 20.04.
/opt/doraemon/deps/abseil-20211102.0/lib
/opt/doraemon/deps/abseil-20211102.0/lib64
/opt/doraemon/deps/ortools-9.9/lib
/opt/doraemon/deps/ortools-9.9/lib64
/opt/doraemon/deps/fields2cover-2.0.0/lib
/opt/doraemon/deps/fields2cover-2.0.0/lib64
/opt/doraemon/deps/flirt-doraemon-20260319/lib
/opt/doraemon/deps/flirt-doraemon-20260319/lib64
