# Fixed commercial dependency environment for interactive maintenance shells.
export DORAEMON_DEPS_ROOT="/opt/doraemon/deps"
export DORAEMON_CMAKE_ROOT="/opt/doraemon/deps/cmake-3.20.6"
export DORAEMON_CMAKE_BIN="/opt/doraemon/deps/cmake-3.20.6/bin/cmake"
export DORAEMON_CTEST_BIN="/opt/doraemon/deps/cmake-3.20.6/bin/ctest"
export DORAEMON_GCC_VERSION="10.5.0"
export CC="/usr/bin/gcc-10"
export CXX="/usr/bin/g++-10"
export ABSEIL_ROOT="/opt/doraemon/deps/abseil-20211102.0"
export ORTOOLS_ROOT="/opt/doraemon/deps/ortools-9.9"
export FIELDS2COVER_ROOT="/opt/doraemon/deps/fields2cover-2.0.0"
export FLIRT_ROOT="/opt/doraemon/deps/flirt-doraemon-20260319"
export absl_DIR="/opt/doraemon/deps/abseil-20211102.0/lib/cmake/absl"
export CMAKE_PREFIX_PATH="/opt/doraemon/deps/abseil-20211102.0:/opt/doraemon/deps/ortools-9.9:/opt/doraemon/deps/fields2cover-2.0.0:/opt/doraemon/deps/flirt-doraemon-20260319${CMAKE_PREFIX_PATH:+:${CMAKE_PREFIX_PATH}}"
export PYTHONPATH="/opt/doraemon/deps/fields2cover-2.0.0/lib/python3.8/site-packages${PYTHONPATH:+:${PYTHONPATH}}"
export PATH="/opt/doraemon/deps/cmake-3.20.6/bin:${PATH}"
